# Generated by Django 5.2.7 on 2025-11-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0002_stanowisko_osoba'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(auto_now_add=True, default='2025-11-07'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.CharField(choices=[(1, 'Mezczyzna'), (2, 'Kobieta'), (3, 'Inna')], default=3, max_length=1),
        ),
    ]
