# Generated by Django 5.2.7 on 2025-11-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0004_alter_osoba_plec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
    ]
